import { createContext, useContext, useState } from "react";
import { Save, Rocket, Image, Settings, Trash2, Reply } from "lucide-react";
// Admin UI translations
const T = {
  fr: {
    // Sidebar
    general:      "GÉNÉRAL",
    content:      "CONTENU",
    communication:"COMMUNICATION",
    system:       "SYSTÈME",
    dashboard:    "Tableau de bord",
    hero_slides:  "Slides Hero",
    news:         "Actualités",
    parishes:     "Paroisses",
    messages:     "Messages",
    settings:     "Paramètres",
    users:        "Utilisateurs",
    logout:       "Déconnexion",
    logged_as:    "Connecté en tant que",

    // Login
    admin_portal: "Portail Administratif",
    diocese:      "Diocèse de Kabgayi",
    email:        "Email",
    password:     "Mot de passe",
    sign_in:      "Se connecter",
    signing_in:   "Connexion...",
    restricted:   "Accès réservé au personnel autorisé",
    back_site:    "← Retour au site",

    // Dashboard
    unread:       "Non lus",
    recent_news:  "Dernières actualités",
    recent_msgs:  "Messages récents",
    view_all:     "Voir tout →",
    published:    "Publié",
    draft:        "Brouillon",
    no_articles:  "Aucun article",
    no_messages:  "Aucun message",
    status:       "Statut",
    date:         "Date",
    from:         "De",
    subject:      "Sujet",
    new_msg:      "Nouveau",
    read:         "Lu",

    // Hero
    hero_title:     "Slides Hero",
    hero_sub:       "Gérez les diapositives de la section héro",
    new_slide:      "+ Nouveau slide",
    badge:          "Badge",
    image_url:      "URL de l'image",
    display_order:  "Ordre d'affichage",
    title_label:    "Titre",
    description:    "Description",
    point:          "Point",
    edit_slide:     "Modifier le slide",
    new_slide_form: "Nouveau slide",
    saving:         "Enregistrement...",
    save:           "Enregistrer",
    cancel:         "Annuler",
    delete_confirm: "Supprimer cette diapositive ?",
    saved:          "Slide enregistré !",
    deleted:        "Supprimé",

    // News
    news_title:    "Actualités",
    news_sub:      "Gérez les articles publiés sur le site",
    new_article:   "+ Nouvel article",
    title_col:     "Titre",
    category_col:  "Catégorie",
    author_col:    "Auteur",
    edit_article:  "Modifier l'article",
    new_article_f: "Nouvel article",
    back_news:     "← Actualités",
    save_draft:    "💾 Brouillon",
    publish:       "🚀 Publier",
    publishing:    "Enregistrement...",
    published_ok:  "Publié avec succès !",
    draft_ok:      "Brouillon sauvegardé",
    publish_now:   "Publier immédiatement",
    category:      "Catégorie",
    excerpt:       "Résumé",
    full_content:  "Contenu complet",
    image_section: "🖼️ Image",
    options:       "⚙️ Options",
    // delete_article:"🗑️ Supprimer l'article",
    image_url_ph:  "https://...",
    cat_ph:        "ex: ORDINATION, PÈLERINAGE...",

    // Parishes
    parishes_title: "Paroisses",
    parishes_sub:   "Gérez les paroisses du diocèse",
    new_parish:     "+ Nouvelle paroisse",
    location_col:   "Lieu",
    vicar_col:      "Vicaire",
    active:         "Active",
    inactive:       "Inactive",
    edit_parish:    "Modifier la paroisse",
    new_parish_f:   "Nouvelle paroisse",
    name_label:     "Nom",
    location_label: "Lieu",
    vicar_label:    "Vicaire / Curé",
    phone_label:    "Téléphone",
    email_label:    "Email",
    desc_label:     "Description",
    order_label:    "Ordre",
    active_label:   "Active",

    // Messages
    msgs_title:    "Messages de contact",
    no_subject:    "(sans sujet)",
    delete_msg:    "🗑️ Supprimer",
    reply_email:   "↩️ Répondre par email",
    select_msg:    "Sélectionnez un message pour le lire",

    // Settings
    settings_title: "Paramètres du site",
    settings_sub:   "Modifiez les informations générales du site",
    save_settings:  "💾 Enregistrer les paramètres",
    settings_saved: "Paramètres enregistrés !",
    general_info:   "Informations générales",
    contact_info:   "Contact",
    social_media:   "Réseaux sociaux",

    // Users
    users_title:    "Utilisateurs",
    users_sub:      "Gérez les accès au portail administratif",
    new_user:       "+ Nouvel utilisateur",
    name_col:       "Nom",
    email_col:      "Email",
    role_col:       "Rôle",
    created_col:    "Créé le",
    me_label:       "Moi",
    edit_user:      "Modifier l'utilisateur",
    new_user_f:     "Nouvel utilisateur",
    new_password:   "Nouveau mot de passe",
    keep_blank:     "Laisser vide pour ne pas changer",
    role_editor:    "Éditeur",
    role_admin:     "Administrateur",
    role_super:     "Super Admin",
    cannot_delete_self: "Vous ne pouvez pas supprimer votre propre compte",
    user_created:   "Utilisateur créé",
    user_updated:   "Utilisateur mis à jour",
  },

  en: {
    general:      "GENERAL",
    content:      "CONTENT",
    communication:"COMMUNICATION",
    system:       "SYSTEM",
    dashboard:    "Dashboard",
    hero_slides:  "Hero Slides",
    news:         "News",
    parishes:     "Parishes",
    messages:     "Messages",
    settings:     "Settings",
    users:        "Users",
    logout:       "Logout",
    logged_as:    "Logged in as",

    admin_portal: "Administration Portal",
    diocese:      "Diocese of Kabgayi",
    email:        "Email",
    password:     "Password",
    sign_in:      "Sign in",
    signing_in:   "Signing in...",
    restricted:   "Access restricted to authorized personnel",
    back_site:    "← Back to website",

    unread:       "Unread",
    recent_news:  "Latest news",
    recent_msgs:  "Recent messages",
    view_all:     "View all →",
    published:    "Published",
    draft:        "Draft",
    no_articles:  "No articles",
    no_messages:  "No messages",
    status:       "Status",
    date:         "Date",
    from:         "From",
    subject:      "Subject",
    new_msg:      "New",
    read:         "Read",

    hero_title:     "Hero Slides",
    hero_sub:       "Manage the hero section slides",
    new_slide:      "+ New slide",
    badge:          "Badge",
    image_url:      "Image URL",
    display_order:  "Display order",
    title_label:    "Title",
    description:    "Description",
    point:          "Point",
    edit_slide:     "Edit slide",
    new_slide_form: "New slide",
    saving:         "Saving...",
    save:           "Save",
    cancel:         "Cancel",
    delete_confirm: "Delete this slide?",
    saved:          "Slide saved!",
    deleted:        "Deleted",

    news_title:    "News",
    news_sub:      "Manage published articles",
    new_article:   "+ New article",
    title_col:     "Title",
    category_col:  "Category",
    author_col:    "Author",
    edit_article:  "Edit article",
    new_article_f: "New article",
    back_news:     "← News",
    save_draft:    "💾 Draft",
    publish:       "🚀 Publish",
    publishing:    "Saving...",
    published_ok:  "Published successfully!",
    draft_ok:      "Draft saved",
    publish_now:   "Publish immediately",
    category:      "Category",
    excerpt:       "Summary",
    full_content:  "Full content",
    image_section: "🖼️ Image",
    options:       "⚙️ Options",
    delete_article:"🗑️ Delete article",
    image_url_ph:  "https://...",
    cat_ph:        "e.g.: ORDINATION, PILGRIMAGE...",

    parishes_title: "Parishes",
    parishes_sub:   "Manage diocese parishes",
    new_parish:     "+ New parish",
    location_col:   "Location",
    vicar_col:      "Vicar",
    active:         "Active",
    inactive:       "Inactive",
    edit_parish:    "Edit parish",
    new_parish_f:   "New parish",
    name_label:     "Name",
    location_label: "Location",
    vicar_label:    "Vicar / Parish Priest",
    phone_label:    "Phone",
    email_label:    "Email",
    desc_label:     "Description",
    order_label:    "Order",
    active_label:   "Active",

    msgs_title:    "Contact messages",
    no_subject:    "(no subject)",
    delete_msg:    "🗑️ Delete",
    reply_email:   "↩️ Reply by email",
    select_msg:    "Select a message to read it",

    settings_title: "Site settings",
    settings_sub:   "Edit general site information",
    save_settings:  "💾 Save settings",
    settings_saved: "Settings saved!",
    general_info:   "General information",
    contact_info:   "Contact",
    social_media:   "Social media",

    users_title:    "Users",
    users_sub:      "Manage admin portal access",
    new_user:       "+ New user",
    name_col:       "Name",
    email_col:      "Email",
    role_col:       "Role",
    created_col:    "Created",
    me_label:       "Me",
    edit_user:      "Edit user",
    new_user_f:     "New user",
    new_password:   "New password",
    keep_blank:     "Leave blank to keep unchanged",
    role_editor:    "Editor",
    role_admin:     "Administrator",
    role_super:     "Super Admin",
    cannot_delete_self: "You cannot delete your own account",
    user_created:   "User created",
    user_updated:   "User updated",
  },

  rw: {
    general:      "RUSANGE",
    content:      "IBIKUBIYEMO",
    communication:"ITUMANAHANA",
    system:       "SISITEME",
    dashboard:    "Imbonerahamwe",
    hero_slides:  "Ibyapa Bibanza",
    news:         "Amakuru",
    parishes:     "Paruwasi",
    messages:     "Ubutumwa",
    settings:     "Igenamiterere",
    users:        "Abakoresha",
    logout:       "Sohoka",
    logged_as:    "Winjiye nka",

    admin_portal: "Portail ya Ubuyobozi",
    diocese:      "Diyosezi ya Kabgayi",
    email:        "Imeyili",
    password:     "Ijambo ryibanga",
    sign_in:      "Injira",
    signing_in:   "Kwinjira...",
    restricted:   "Kwinjira gufungiwe abafite uburenganzira",
    back_site:    "← Subira ku rubuga",

    unread:       "Bitasomwe",
    recent_news:  "Amakuru mashya",
    recent_msgs:  "Ubutumwa bushya",
    view_all:     "Reba byose →",
    published:    "Byatangazwe",
    draft:        "Mpiti",
    no_articles:  "Nta makuru",
    no_messages:  "Nta butumwa",
    status:       "Imimerere",
    date:         "Italiki",
    from:         "Uturutse",
    subject:      "Inyito",
    new_msg:      "Gsha",
    read:         "Basomye",

    hero_title:     "Ibyapa Bibanza",
    hero_sub:       "Genzura ibyapa bya Hero",
    new_slide:      "+ Ibyapa gishya",
    badge:          "Ikimenyetso",
    image_url:      "Aderesi y'ishusho",
    display_order:  "Urutonde rw'igaragazwa",
    title_label:    "Umutwe",
    description:    "Ibisobanuro",
    point:          "Ingingo",
    edit_slide:     "Hindura ibyapa",
    new_slide_form: "Ibyapa gishya",
    saving:         "Kubika...",
    save:           "Bika",
    cancel:         "Kureka",
    delete_confirm: "Gusiba iki cyapa?",
    saved:          "Ibyapa birabitswe!",
    deleted:        "Basibwe",

    news_title:    "Amakuru",
    news_sub:      "Genzura inkuru zatangazwe ku rubuga",
    new_article:   "+ Inkuru nshya",
    title_col:     "Umutwe",
    category_col:  "Icyiciro",
    author_col:    "Uwanditse",
    edit_article:  "Hindura inkuru",
    new_article_f: "Inkuru nshya",
    back_news:     "← Amakuru",
    save_draft:    "💾 Bika Mpiti",
    publish:       "🚀 Tangaza",
    publishing:    "Kubika...",
    published_ok:  "Byatangazwe!",
    draft_ok:      "Mpiti ibitswe",
    publish_now:   "Tangaza ubu",
    category:      "Icyiciro",
    excerpt:       "Incamake",
    full_content:  "Inyandiko yuzuye",
    image_section: "🖼️ Ishusho",
    options:       "⚙️ Ibindi",
    delete_article:"🗑️ Siba inkuru",
    image_url_ph:  "https://...",
    cat_ph:        "urugero: UBUPADIRI, URUGENDO...",

    parishes_title: "Paruwasi",
    parishes_sub:   "Genzura paruwasi za diyosezi",
    new_parish:     "+ Paruwasi nshya",
    location_col:   "Ahantu",
    vicar_col:      "Umupadiri",
    active:         "Ikora",
    inactive:       "Ntikora",
    edit_parish:    "Hindura paruwasi",
    new_parish_f:   "Paruwasi nshya",
    name_label:     "Izina",
    location_label: "Ahantu",
    vicar_label:    "Umupadiri",
    phone_label:    "Telefoni",
    email_label:    "Imeyili",
    desc_label:     "Ibisobanuro",
    order_label:    "Urutonde",
    active_label:   "Ikora",

    msgs_title:    "Ubutumwa bw'itwazwa",
    no_subject:    "(Nta nyito)",
    delete_msg:    "🗑️ Siba",
    reply_email:   "↩️ Subiza kuri imeyili",
    select_msg:    "Hitamo ubutumwa ngo ubusome",

    settings_title: "Igenamiterere ry'urubuga",
    settings_sub:   "Hindura amakuru rusange y'urubuga",
    save_settings:  "💾 Bika igenamiterere",
    settings_saved: "Igenamiterere rirabitswe!",
    general_info:   "Amakuru rusange",
    contact_info:   "Twunganire",
    social_media:   "Imiyoboro ya sosiyali",

    users_title:    "Abakoresha",
    users_sub:      "Genzura ubufatanye mu portail ya admin",
    new_user:       "+ Umukosha mushya",
    name_col:       "Amazina",
    email_col:      "Imeyili",
    role_col:       "Uruhare",
    created_col:    "Yaremwe",
    me_label:       "Ndi jye",
    edit_user:      "Hindura umukosha",
    new_user_f:     "Umukosha mushya",
    new_password:   "Ijambo rishya ryibanga",
    keep_blank:     "Siga ubusa kutahindura",
    role_editor:    "Umwanditsi",
    role_admin:     "Umuyobozi",
    role_super:     "Super Admin",
    cannot_delete_self: "Ntushobora gusiba konti yawe",
    user_created:   "Umukosha yaremwe",
    user_updated:   "Umukosha yahinduwe",
  },
};

const AdminLangContext = createContext();

export function AdminLangProvider({ children }) {
  const [lang, setLang] = useState(
    localStorage.getItem("admin_lang") || "fr"
  );

  const changeLang = (l) => {
    setLang(l);
    localStorage.setItem("admin_lang", l);
  };

  const t = (key) => T[lang]?.[key] || T["fr"]?.[key] || key;

  return (
    <AdminLangContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </AdminLangContext.Provider>
  );
}

export const useAdminLang = () => useContext(AdminLangContext);
